// Simple editor to view/modify major data objects and download an updated data.js
(function () {
    const select = document.getElementById('dataSelect');
    const editor = document.getElementById('jsonEditor');
    const loadBtn = document.getElementById('loadBtn');
    const validateBtn = document.getElementById('validateBtn');
    const applyBtn = document.getElementById('applyBtn');
    const downloadBtn = document.getElementById('downloadBtn');
    const reloadOriginalBtn = document.getElementById('reloadOriginalBtn');

    const dataKeys = ['translations', 'iconsAndRefs', 'teamMembers', 'projects', 'publications2025', 'events2025'];

    function safeGet(key) {
        try { return window[key]; } catch (e) { return undefined; }
    }

    function loadSelected() {
        const key = select.value;
        const val = safeGet(key);
        if (val === undefined) {
            editor.value = `// ${key} is not defined in the current page environment.`;
            return;
        }
        try {
            editor.value = JSON.stringify(val, null, 4);
        } catch (e) {
            editor.value = `// Could not stringify ${key}: ` + e.message;
        }
    }

    function validateJSON() {
        try {
            JSON.parse(editor.value);
            alert('Valid JSON');
        } catch (e) {
            alert('Invalid JSON: ' + e.message);
        }
    }

    function applyChanges() {
        const key = select.value;
        try {
            const parsed = JSON.parse(editor.value);
            window[key] = parsed;
            // Re-render known components if available
            if (typeof renderTeam === 'function') renderTeam();
            if (typeof renderProjects === 'function') renderProjects();
            if (typeof renderPublications === 'function') renderPublications();
            if (typeof renderEvents === 'function') renderEvents();
            if (typeof renderProfile === 'function') renderProfile();
            alert('Applied changes to ' + key + ' and re-rendered components if present.');
        } catch (e) {
            alert('Failed to apply: Invalid JSON - ' + e.message);
        }
    }

    function buildDataJsContent() {
        // Generate a replacement data.js content using current in-memory values.
        const parts = [];
        parts.push('// Generated by data-editor');
        dataKeys.forEach(k => {
            const val = safeGet(k);
            if (val === undefined) return;
            const str = JSON.stringify(val, null, 4);
            parts.push(`const ${k} = ${str};\n`);
        });
        parts.push('// End of generated data');
        return parts.join('\n');
    }

    function downloadDataJs() {
        const content = buildDataJsContent();
        const blob = new Blob([content], { type: 'text/javascript' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'data.js';
        document.body.appendChild(a);
        a.click();
        a.remove();
        URL.revokeObjectURL(url);
    }

    async function reloadOriginal() {
        try {
            const resp = await fetch('javascript/data.js');
            if (!resp.ok) throw new Error('Failed to fetch original data.js');
            const txt = await resp.text();
            editor.value = txt;
            alert('Original file loaded into editor textarea (raw JS).');
        } catch (e) {
            alert('Could not reload original: ' + e.message);
        }
    }

    // Event wiring
    loadBtn.addEventListener('click', loadSelected);
    validateBtn.addEventListener('click', validateJSON);
    applyBtn.addEventListener('click', applyChanges);
    downloadBtn.addEventListener('click', downloadDataJs);
    reloadOriginalBtn.addEventListener('click', reloadOriginal);

    // Initial load
    loadSelected();
})();
