// Language translations
// Language translations
const translations = {
    en: {
        robin_director: "Director of the Study Center",
        robin_specialty: "B.Sc. in Computer Science",
        main_title: "CAD/CAM Study Center",
        nav_about: "About",
        nav_mission: "Mission",
        nav_programs: "Programs",
        nav_team: "Team",
        nav_research: "Research",
        nav_projects: "Projects",
        nav_collaborations: "Collaborations",
        hero_title: "COMPUTER-AIDED DESIGN AND MANUFACTURING",
        hero_subtitle: "A leading Study Center with 30 years of experience developing engineering research projects that impact the university, the region, and the nation",
        hero_btn: "Learn More",
        about_title: "About Us",
        about_text1: "The CAD/CAM Study Center at the University of Holguín is the first and only center of its kind within Cuba's Ministry of Higher Education. Founded in 1985 as a research group, it became an official center in 1989.",
        about_text2: "Our initial mission was the development of mechanical engineering software for clients in national and international markets, including Colombia, Mexico, Spain, and Switzerland.",
        about_text3: "Today, we continue to be pioneers in engineering research and education, with a focus on CAD/CAM/CAE technologies.",
        mission_title: "Our Mission",
        mission_text: "Our mission is to provide high-quality undergraduate and postgraduate education and to apply our research to solving scientific-technical problems, all through a strong university-community partnership and a team of experts with solid scientific training in CAD/CAM/CAE technologies.",
        programs_title: "Academic Programs",
        programs_undergraduate: "Undergraduate Studies",
        programs_mechanical: "Mechanical Engineering",
        programs_civil: "Civil Engineering",
        programs_electrical: "Electrical Engineering",
        programs_postgraduate: "Postgraduate Studies",
        programs_masters: "Master's in CAD/CAM (Recognized for Excellence)",
        programs_phd: "PhD programs participation",
        programs_engineering: "Engineering Development (UHo)",
        programs_business: "Business Management (UHo)",
        programs_industrial: "Industrial Technology and Processes (UMatanzas)",
        team_title: "Our Team",
        research_title: "Research Conception",
        research_digital: "Digital Models",
        research_digital_text: "Numerical simulations, mathematical modeling, predictive analysis, and proactive risk management",
        research_physical: "Physical Models",
        research_physical_text: "Prototyping and testing of physical models for validation and improvement of designs",
        research_cyber: "Cyber-Physical Systems",
        research_cyber_text: "Integration of computational and physical components for advanced engineering solutions",
        experience_title: "Our Experience",
        experience_machinery: "Machinery Sector",
        experience_infrastructure: "Infrastructure Sector",
        experience_health: "Health Sector",
        experience_machinery_title: "Land Leveler for Rice Fields",
        experience_machinery_text: "Development of specialized machinery for agricultural applications, improving efficiency and productivity in rice cultivation.",
        experience_infrastructure_title: "Infrastructure Projects",
        experience_infrastructure_text: "Application of CAD/CAM technologies in the design and construction of infrastructure projects, ensuring precision and durability.",
        experience_health_title: "Healthcare Solutions",
        experience_health_text: "Development of medical devices and surgical models using advanced manufacturing techniques to improve patient care.",
        projects_title: "Research Projects",
        project1_title: "Disruptive Tools for Teaching Engineering",
        project1_desc: "Focused on Energy, the Environment, and Occupational Safety and Health: A View from the STEM Approach",
        project1_program: "Sectorial Program: Higher Education and Sustainable Development",
        project1_period: "2024-2026",
        project2_title: "Contributions to the Sustainability of Power Generator Sets",
        project2_desc: "Comprehensive diagnosis of the operation and maintenance process, defining failure causes, and developing maintenance policies",
        project2_program: "Territorial Program: Energy",
        project2_period: "2023-2024",
        project3_title: "Tropicalization of Wind Turbines",
        project3_desc: "Maintenance of cooling systems in wind turbines, CAE simulation of temperature behavior, and maintenance policy development",
        project3_program: "Territorial Program: Energy",
        project3_period: "2021-2023",
        project4_title: "Cuban Self-Ballasted Support",
        project4_desc: "Self-ballasted photovoltaic park installations for roofs or ground surfaces, with adjustable mounting design and safety accessories",
        project4_program: "Scientific Technical Service",
        project4_period: "2023-2024",
        project5_title: "Controller for the Computer-Assisted Operation and Maintenance of the Mayarí Power Plant",
        project5_desc: "Development of intelligent control systems for power plant operation and maintenance optimization",
        project5_program: "Territorial Program: Energy Transformation of Holguín Province",
        project5_period: "2025-2028",
        project6_title: "Vulnerability of Mining Sites to Subsidence Based on INSAR Technology",
        project6_desc: "Analysis and monitoring of mining areas using Interferometric Synthetic Aperture Radar technology",
        project6_program: "National Program: Basic and Natural Sciences",
        project6_period: "2021-2023",
        project7_title: "Geomatics-BIM Integration for Improving Project Management and Construction Control",
        project7_desc: "Integration of geomatics and Building Information Modeling for enhanced project management",
        project7_program: "Sectorial Program: Development of Systems and Technologies for Investment Optimization",
        project7_period: "2021-2025",
        project8_title: "Improvement of the CCA-6000 (CCA-5000M) Sugarcane Harvester",
        project8_desc: "Enhancement of sugarcane harvesting machinery for improved efficiency and productivity",
        project8_program: "Territorial Program: Industry in Cuba",
        project8_period: "2025-2028",
        project9_title: "Increasing the Structural and Energy Resilience of Houses with Lightweight Roofs",
        project9_desc: "Enhancing resistance of lightweight roof structures against extreme wind impacts",
        project9_program: "Sectorial Program: Integrated Disaster Risk Reduction in Cuba",
        project9_period: "2025-2028",
        project10_title: "Impact of Monumental Heritage on Tourism Development in Municipalities of Holguín",
        project10_desc: "Analysis of heritage sites' contribution to sustainable tourism development in the region",
        project10_program: "Territorial Program: Holguín, a Smart and Sustainable Tourist Destination",
        project10_period: "2025-2028",
        project11_title: "Transformation of Surgical Practice through Additive Manufacturing",
        project11_desc: "Incorporation of 3D printing technology in the production of surgical models for pediatric hospital",
        project11_program: "Collaboration Project: Research in Science and Technology for Human Development",
        project11_period: "2023-2025",
        project12_title: "Early Prediction of Motor Progression in Spinocerebellar Ataxias Using AI",
        project12_desc: "Development of artificial intelligence tools for early prediction of motor progression in neurological disorders",
        project12_program: "National Program: Neurosciences and Neurotechnology",
        project12_period: "2024-2026",
        collaborations_title: "International Collaborations",
        footer_about: "About Us",
        footer_about_text: "CAD/CAM Study Center at the University of Holguín, pioneering engineering research and education for over 30 years.",
        footer_links: "Quick Links",
        footer_about_link: "About Us",
        footer_programs_link: "Programs",
        footer_research_link: "Research",
        footer_projects_link: "Projects",
        footer_contact: "Contact",
        footer_follow: "Follow Us",
        footer_rights: "All Rights Reserved."
    },
    es: {
        robin_director: "Director del Centro de Estudios",
        robin_specialty: "Lic. en Ciencias de la Computación",
        main_title: "Centro de Estudios CAD/CAM",
        nav_about: "Acerca de",
        nav_mission: "Misión",
        nav_programs: "Programas",
        nav_team: "Equipo",
        nav_research: "Investigación",
        nav_projects: "Proyectos",
        nav_collaborations: "Colaboraciones",
        hero_title: "DISEÑO Y FABRICACIÓN ASISTIDOS POR COMPUTADORA",
        hero_subtitle: "Un Centro de Estudios líder con 30 años de experiencia desarrollando proyectos de investigación en ingeniería que impactan la universidad, la región y la nación",
        hero_btn: "Más Información",
        about_title: "Acerca de Nosotros",
        about_text1: "El Centro de Estudios CAD/CAM de la Universidad de Holguín es el primer y único centro de su tipo dentro del Ministerio de Educación Superior de Cuba. Fundado en 1985 como grupo de investigación, se convirtió en un centro oficial en 1989.",
        about_text2: "Nuestra misión inicial fue el desarrollo de software de ingeniería mecánica para clientes en mercados nacionales e internacionales, incluyendo Colombia, México, España y Suiza.",
        about_text3: "Hoy, continuamos siendo pioneros en investigación y educación en ingeniería, con un enfoque en tecnologías CAD/CAM/CAE.",
        mission_title: "Nuestra Misión",
        mission_text: "Nuestra misión es proporcionar educación de pregrado y posgrado de alta calidad y aplicar nuestra investigación a la resolución de problemas científico-técnicos, todo a través de una sólida asociación universidad-comunidad y un equipo de expertos con formación científica sólida en tecnologías CAD/CAM/CAE.",
        programs_title: "Programas Académicos",
        programs_undergraduate: "Estudios de Pregrado",
        programs_mechanical: "Ingeniería Mecánica",
        programs_civil: "Ingeniería Civil",
        programs_electrical: "Ingeniería Eléctrica",
        programs_postgraduate: "Estudios de Posgrado",
        programs_masters: "Maestría en CAD/CAM (Reconocida por su Excelencia)",
        programs_phd: "Participación en programas de Doctorado",
        programs_engineering: "Desarrollo de Ingeniería (UHo)",
        programs_business: "Gestión de Empresas (UHo)",
        programs_industrial: "Tecnología y Procesos Industriales (UMatanzas)",
        team_title: "Nuestro Equipo",
        research_title: "Concepción de la Investigación",
        research_digital: "Modelos Digitales",
        research_digital_text: "Simulaciones numéricas, modelado matemático, análisis predictivo y gestión proactiva de riesgos",
        research_physical: "Modelos Físicos",
        research_physical_text: "Prototipado y prueba de modelos físicos para validación y mejora de diseños",
        research_cyber: "Sistemas Ciber-Físicos",
        research_cyber_text: "Integración de componentes computacionales y físicos para soluciones de ingeniería avanzadas",
        experience_title: "Nuestra Experiencia",
        experience_machinery: "Sector de Maquinaria",
        experience_infrastructure: "Sector de Infraestructura",
        experience_health: "Sector de la Salud",
        experience_machinery_title: "Niveladora de Tierra para Arrozales",
        experience_machinery_text: "Desarrollo de maquinaria especializada para aplicaciones agrícolas, mejorando la eficiencia y productividad en el cultivo de arroz.",
        experience_infrastructure_title: "Proyectos de Infraestructura",
        experience_infrastructure_text: "Aplicación de tecnologías CAD/CAM en el diseño y construcción de proyectos de infraestructura, garantizando precisión y durabilidad.",
        experience_health_title: "Soluciones de Salud",
        experience_health_text: "Desarrollo de dispositivos médicos y modelos quirúrgicos utilizando técnicas de fabricación avanzadas para mejorar la atención al paciente.",
        projects_title: "Proyectos de Investigación",
        project1_title: "Herramientas Disruptivas para la Enseñanza de la Ingeniería",
        project1_desc: "Enfocadas en Energía, el Medio Ambiente y la Seguridad y Salud Ocupacional: Una Visión desde el Enfoque STEM",
        project1_program: "Programa Sectorial: Educación Superior y Desarrollo Sostenible",
        project1_period: "2024-2026",
        project2_title: "Contribuciones a la Sostenibilidad de Grupos Electrógenos",
        project2_desc: "Diagnóstico integral del proceso de operación y mantenimiento, definición de causas de fallos y desarrollo de políticas de mantenimiento",
        project2_program: "Programa Territorial: Energía",
        project2_period: "2023-2024",
        project3_title: "Tropicalización de Aerogeneradores",
        project3_desc: "Mantenimiento de sistemas de enfriamiento en aerogeneradores, simulación CAE del comportamiento de temperaturas y desarrollo de políticas de mantenimiento",
        project3_program: "Programa Territorial: Energía",
        project3_period: "2021-2023",
        project4_title: "Soporte Autobalanceado Cubano",
        project4_desc: "Instalaciones de parques fotovoltaicos autobalanceados para techos o superficies terrestres, con diseño de montaje ajustable y accesorios de seguridad",
        project4_program: "Servicio Científico Técnico",
        project4_period: "2023-2024",
        project5_title: "Controlador para la Operación y Mantenimiento Asistido por Computadora de la Planta de Energía de Mayarí",
        project5_desc: "Desarrollo de sistemas de control inteligentes para la optimización de la operación y mantenimiento de la planta de energía",
        project5_program: "Programa Territorial: Transformación Energética de la Provincia Holguín",
        project5_period: "2025-2028",
        project6_title: "Vulnerabilidad de Sitios Mineros a la Subsidencia Basada en el Uso de Tecnología INSAR",
        project6_desc: "Análisis y monitoreo de áreas mineras utilizando tecnología de Radar de Apertura Sintética Interferométrico",
        project6_program: "Programa Nacional: Ciencias Básicas y Naturales",
        project6_period: "2021-2023",
        project7_title: "Integración Geomática-BIM para Mejorar la Gestión de Proyectos y Control de Construcción",
        project7_desc: "Integración de geomática y Modelado de Información de Edificios para una gestión de proyectos mejorada",
        project7_program: "Programa Sectorial: Desarrollo de Sistemas y Tecnologías para la Optimización de las Inversiones",
        project7_period: "2021-2025",
        project8_title: "Mejora de la Cosechadora de Caña de Azúcar CCA-6000 (CCA-5000M)",
        project8_desc: "Mejoramiento de maquinaria de cosecha de caña de azúcar para mayor eficiencia y productividad",
        project8_program: "Programa Territorial: Industria en Cuba",
        project8_period: "2025-2028",
        project9_title: "Aumento de la Resiliencia Estructural y Energética de Viviendas con Techos Ligeros",
        project9_desc: "Mejora de la resistencia de estructuras de techos ligeros contra impactos de vientos extremos",
        project9_program: "Programa Sectorial: Reducción Integrada del Riesgo de Desastres en Cuba",
        project9_period: "2025-2028",
        project10_title: "Impacto del Patrimonio Monumental en el Desarrollo Turístico en Municipios de Holguín",
        project10_desc: "Análisis de la contribución de sitios patrimoniales al desarrollo turístico sostenible en la región",
        project10_program: "Programa Territorial: Holguín, un Destino Turístico Inteligente y Sostenible",
        project10_period: "2025-2028",
        project11_title: "Transformación de la Práctica Quirúrgica a través de la Fabricación Aditiva",
        project11_desc: "Incorporación de tecnología de impresión 3D en la producción de modelos quirúrgicos para hospital pediátrico",
        project11_program: "Proyecto de Colaboración: Investigación en Ciencia y Tecnología para el Desarrollo Humano",
        project11_period: "2023-2025",
        project12_title: "Predicción Temprana de la Progresión Motora en Ataxias Espinocerebelosas Usando IA",
        project12_desc: "Desarrollo de herramientas de inteligencia artificial para la predicción temprana de la progresión motora en trastornos neurológicos",
        project12_program: "Programa Nacional: Neurociencias y Neurotecnología",
        project12_period: "2024-2026",
        collaborations_title: "Colaboraciones Internacionales",
        footer_about: "Acerca de",
        footer_about_text: "Centro de Estudios CAD/CAM de la Universidad de Holguín, pioneros en investigación y educación en ingeniería por más de 30 años.",
        footer_links: "Enlaces Rápidos",
        footer_about_link: "Acerca de",
        footer_programs_link: "Programas",
        footer_research_link: "Investigación",
        footer_projects_link: "Proyectos",
        footer_contact: "Contacto",
        footer_follow: "Síguenos",
        footer_rights: "Todos los Derechos Reservados."
    },
    ru: {
        robin_director: "Director of the Study Center",
        robin_specialty: "B.Sc. in Computer Science",
        main_title: "CAD/CAM Study Center",
        nav_about: "О нас",
        nav_mission: "Миссия",
        nav_programs: "Программы",
        nav_team: "Команда",
        nav_research: "Исследования",
        nav_projects: "Проекты",
        nav_collaborations: "Сотрудничество",
        hero_title: "КОМПЬЮТЕРНОЕ ПРОЕКТИРОВАНИЕ И КОМПЬЮТЕРНОЕ УПРАВЛЕНИЕ ПРОИЗВОДСТВОМ",
        hero_subtitle: "Ведущий учебный центр с 30-летним опытом разработки инженерных исследовательских проектов, влияющих на университет, регион и страну",
        hero_btn: "Узнать больше",
        about_title: "О нас",
        about_text1: "Центр исследований CAD/CAM Университета Ольгина является первым и единственным центром своего рода в рамках Министерства высшего образования Кубы. Основанный в 1985 году как исследовательская группа, он стал официальным центром в 1989 году.",
        about_text2: "Нашей первоначальной миссией было разработка программного обеспечения для машиностроения для клиентов на национальных и международных рынках, включая Колумбию, Мексику, Испанию и Швейцарию.",
        about_text3: "Сегодня мы продолжаем быть пионерами в инженерных исследованиях и образовании, с фокусом на технологии CAD/CAM/CAE.",
        mission_title: "Наша миссия",
        mission_text: "Наша миссия - предоставлять высококачественное образование на уровне бакалавриата и магистратуры и применять наши исследования для решения научно-технических проблем, все через прочное партнерство между университетом и сообществом и команду экспертов с солидной научной подготовкой в технологиях CAD/CAM/CAE.",
        programs_title: "Академические программы",
        programs_undergraduate: "Программы бакалавриата",
        programs_mechanical: "Машиностроение",
        programs_civil: "Строительство",
        programs_electrical: "Электротехника",
        programs_postgraduate: "Программы магистратуры и аспирантуры",
        programs_masters: "Магистратура по CAD/CAM (Признана за превосходство)",
        programs_phd: "Участие в программах PhD",
        programs_engineering: "Разработка инженерии (UHo)",
        programs_business: "Управление бизнесом (UHo)",
        programs_industrial: "Промышленные технологии и процессы (UMatanzas)",
        team_title: "Наша команда",
        research_title: "Концепция исследований",
        research_digital: "Цифровые модели",
        research_digital_text: "Численное моделирование, математическое моделирование, прогнозный анализ и проактивное управление рисками",
        research_physical: "Физические модели",
        research_physical_text: "Прототипирование и тестирование физических моделей для валидации и улучшения дизайна",
        research_cyber: "Кибер-физические системы",
        research_cyber_text: "Интеграция вычислительных и физических компонентов для передовых инженерных решений",
        experience_title: "Наш опыт",
        experience_machinery: "Машиностроительный сектор",
        experience_infrastructure: "Инфраструктурный сектор",
        experience_health: "Сектор здравоохранения",
        experience_machinery_title: "Выравниватель земли для рисовых полей",
        experience_machinery_text: "Разработка специализированной техники для сельскохозяйственных применений, улучшение эффективности и производительности в выращивании риса.",
        experience_infrastructure_title: "Инфраструктурные проекты",
        experience_infrastructure_text: "Применение технологий CAD/CAM в проектировании и строительстве инфраструктурных проектов, обеспечивая точность и долговечность.",
        experience_health_title: "Решения для здравоохранения",
        experience_health_text: "Разработка медицинских устройств и хирургических моделей с использованием передовых производственных техник для улучшения ухода за пациентами.",
        projects_title: "Исследовательские проекты",
        project1_title: "Инновационные инструменты для преподавания инженерии",
        project1_desc: "Сфокусированные на энергетике, окружающей среде и охране труда и здоровья: Взгляд с точки зрения STEM",
        project1_program: "Секторная программа: Высшее образование и устойчивое развитие",
        project1_period: "2024-2026",
        project2_title: "Вклад в устойчивость дизельных электростанций",
        project2_desc: "Комплексная диагностика процесса эксплуатации и технического обслуживания, определение причин отказов и разработка политик технического обслуживания",
        project2_program: "Территориальная программа: Энергетика",
        project2_period: "2023-2024",
        project3_title: "Тропикализация ветряных турбин",
        project3_desc: "Техническое обслуживание систем охлаждения в ветряных турбинах, CAE-моделирование поведения температур и разработка политик технического обслуживания",
        project3_program: "Территориальная программа: Энергетика",
        project3_period: "2021-2023",
        project4_title: "Кубинский самобалансирующий опорный элемент",
        project4_desc: "Самобалансирующиеся установки фотоэлектрических парков для крыш или наземных поверхностей, с регулируемым дизайном монтажа и аксессуарами безопасности",
        project4_program: "Научно-техническая служба",
        project4_period: "2023-2024",
        project5_title: "Контроллер для компьютеризированной эксплуатации и обслуживания электростанции Майари",
        project5_desc: "Разработка интеллектуальных систем управления для оптимизации эксплуатации и обслуживания электростанции",
        project5_program: "Территориальная программа: Энергетическая трансформация провинции Ольгин",
        project5_period: "2025-2028",
        project6_title: "Уязвимость горнодобывающих участков к оседанию на основе технологии INSAR",
        project6_desc: "Анализ и мониторинг горнодобывающих районов с использованием технологии интерферометрического радиолокационного зондирования с синтетической апертурой",
        project6_program: "Национальная программа: Фундаментальные и естественные науки",
        project6_period: "2021-2023",
        project7_title: "Интеграция геоматики и BIM для улучшения управления проектами и контроля строительства",
        project7_desc: "Интеграция геоматики и информационного моделирования зданий для улучшенного управления проектами",
        project7_program: "Секторная программа: Разработка систем и технологий для оптимизации инвестиций",
        project7_period: "2021-2025",
        project8_title: "Улучшение сахарного комбайна CCA-6000 (CCA-5000M)",
        project8_desc: "Модернизация сахарного комбайна для повышения эффективности и производительности",
        project8_program: "Территориальная программа: Промышленность на Кубе",
        project8_period: "2025-2028",
        project9_title: "Повышение структурной и энергетической устойчивости домов с легкими крышами",
        project9_desc: "Усиление сопротивления легких кровельных конструкций воздействию экстремальных ветров",
        project9_program: "Секторная программа: Интегрированное снижение риска бедствий на Кубе",
        project9_period: "2025-2028",
        project10_title: "Влияние монументального наследия на развитие туризма в муниципалитетах Ольгина",
        project10_desc: "Анализ вклада объектов наследия в устойчивое развитие туризма в регионе",
        project10_program: "Территориальная программа: Ольгин, умный и устойчивый туристический центр",
        project10_period: "2025-2028",
        project11_title: "Трансформация хирургической практики через аддитивное производство",
        project11_desc: "Внедрение технологии 3D-печати в производство хирургических моделей для детской больницы",
        project11_program: "Проект сотрудничества: Исследования в области науки и технологий для человеческого развития",
        project11_period: "2023-2025",
        project12_title: "Раннее прогнозирование прогрессирования моторики при спиноцеребеллярных атаксиях с использованием ИИ",
        project12_desc: "Разработка инструментов искусственного интеллекта для раннего прогнозирования прогрессирования моторики при неврологических расстройствах",
        project12_program: "Национальная программа: Нейронауки и нейротехнологии",
        project12_period: "2024-2026",
        collaborations_title: "Международное сотрудничество",
        footer_about: "О нас",
        footer_about_text: "Центр исследований CAD/CAM Университета Ольгина, пионеры в инженерных исследованиях и образовании более 30 лет.",
        footer_links: "Быстрые ссылки",
        footer_about_link: "О нас",
        footer_programs_link: "Программы",
        footer_research_link: "Исследования",
        footer_projects_link: "Проекты",
        footer_contact: "Контакты",
        footer_follow: "Подписывайтесь",
        footer_rights: "Все права защищены."
    },
    zh: {
        robin_director: "Director of the Study Center",
        robin_specialty: "B.Sc. in Computer Science",
        main_title: "CAD/CAM Study Center",
        nav_about: "关于我们",
        nav_mission: "使命",
        nav_programs: "项目",
        nav_team: "团队",
        nav_research: "研究",
        nav_projects: "项目",
        nav_collaborations: "合作",
        hero_title: "计算机辅助设计与计算机辅助制造",
        hero_subtitle: "拥有30年经验的领先研究中心，开发影响大学、地区和国家的工程项目",
        hero_btn: "了解更多",
        about_title: "关于我们",
        about_text1: "奥尔金大学的CAD/CAM研究中心是古巴高等教育部内首个也是唯一一个此类中心。成立于1985年，最初是一个研究小组，于1989年成为正式中心。",
        about_text2: "我们最初的使命是为国内外市场的客户开发机械工程软件，包括哥伦比亚、墨西哥、西班牙和瑞士。",
        about_text3: "今天，我们继续成为工程研究和教育的先驱，专注于CAD/CAM/CAE技术。",
        mission_title: "我们的使命",
        mission_text: "我们的使命是提供高质量的本科和研究生教育，并将我们的研究应用于解决科学技术问题，所有这些都通过强大的大学-社区伙伴关系和一支在CAD/CAM/CAE技术方面具有扎实科学培训的专家团队来实现。",
        programs_title: "学术项目",
        programs_undergraduate: "本科学习",
        programs_mechanical: "机械工程",
        programs_civil: "土木工程",
        programs_electrical: "电气工程",
        programs_postgraduate: "研究生学习",
        programs_masters: "CAD/CAM硕士（以卓越著称）",
        programs_phd: "博士项目参与",
        programs_engineering: "工程发展（UHo）",
        programs_business: "企业管理（UHo）",
        programs_industrial: "工业技术与流程（UMatanzas）",
        team_title: "我们的团队",
        research_title: "研究概念",
        research_digital: "数字模型",
        research_digital_text: "数值模拟、数学建模、预测分析和主动风险管理",
        research_physical: "物理模型",
        research_physical_text: "物理模型的原型制作和测试，用于验证和改进设计",
        research_cyber: "赛博物理系统",
        research_cyber_text: "计算和物理组件的集成，用于先进的工程解决方案",
        experience_title: "我们的经验",
        experience_machinery: "机械部门",
        experience_infrastructure: "基础设施部门",
        experience_health: "卫生部门",
        experience_machinery_title: "稻田平地机",
        experience_machinery_text: "为农业应用开发专用机械，提高水稻种植的效率和生产力。",
        experience_infrastructure_title: "基础设施项目",
        experience_infrastructure_text: "在基础设施项目的设计和施工中应用CAD/CAM技术，确保精度和耐久性。",
        experience_health_title: "医疗解决方案",
        experience_health_text: "使用先进制造技术开发医疗设备和手术模型，以改善患者护理。",
        projects_title: "研究项目",
        project1_title: "工程教学的颠覆性工具",
        project1_desc: "专注于能源、环境和职业安全与健康：从STEM方法的视角",
        project1_program: "部门计划：高等教育和可持续发展",
        project1_period: "2024-2026",
        project2_title: "对发电机组可持续性的贡献",
        project2_desc: "全面诊断操作和维护过程，确定故障原因，并制定维护政策",
        project2_program: "地区计划：能源",
        project2_period: "2023-2024",
        project3_title: "风力涡轮机的热带化",
        project3_desc: "风力涡轮机冷却系统的维护，温度行为的CAE模拟，以及维护政策的制定",
        project3_program: "地区计划：能源",
        project3_period: "2021-2023",
        project4_title: "古巴自平衡支撑",
        project4_desc: "用于屋顶或地面的自平衡光伏公园装置，具有可调节的安装设计和安全配件",
        project4_program: "科学技术服务",
        project4_period: "2023-2024",
        project5_title: "马亚里发电厂计算机辅助运行和维护控制器",
        project5_desc: "开发用于发电厂运行和维护优化的智能控制系统",
        project5_program: "地区计划：奥尔金省能源转型",
        project5_period: "2025-2028",
        project6_title: "基于INSAR技术的矿区沉降脆弱性研究",
        project6_desc: "使用干涉合成孔径雷达技术分析和监测矿区",
        project6_program: "国家计划：基础和自然科学",
        project6_period: "2021-2023",
        project7_title: "地理信息-BIM集成以改善项目管理和施工控制",
        project7_desc: "集成地理信息和建筑信息建模以增强项目管理",
        project7_program: "部门计划：投资优化系统和技术开发",
        project7_period: "2021-2025",
        project8_title: "CCA-6000（CCA-5000M）甘蔗收割机改进",
        project8_desc: "改进甘蔗收割机械以提高效率和生产力",
        project8_program: "地区计划：古巴工业",
        project8_period: "2025-2028",
        project9_title: "提高轻质屋顶房屋的结构和能源抗风能力",
        project9_desc: "增强轻质屋顶结构对极端风影响的抵抗力",
        project9_program: "部门计划：古巴综合灾害风险减少",
        project9_period: "2025-2028",
        project10_title: "奥尔金市镇纪念碑遗产对旅游发展的影响",
        project10_desc: "分析遗产地对区域可持续旅游发展的贡献",
        project10_program: "地区计划：奥尔金，智能可持续旅游目的地",
        project10_period: "2025-2028",
        project11_title: "通过增材制造转变外科实践",
        project11_desc: "在儿童医院手术模型生产中引入3D打印技术",
        project11_program: "合作项目：人类发展科学技术研究",
        project11_period: "2023-2025",
        project12_title: "使用人工智能工具早期预测脊髓小脑性共济失调的运动进展",
        project12_desc: "开发人工智能工具用于早期预测神经系统疾病的运动进展",
        project12_program: "国家计划：神经科学和神经技术",
        project12_period: "2024-2026",
        collaborations_title: "国际合作",
        footer_about: "关于我们",
        footer_about_text: "奥尔金大学的CAD/CAM研究中心，30多年来在工程研究和教育方面处于领先地位。",
        footer_links: "快速链接",
        footer_about_link: "关于我们",
        footer_programs_link: "项目",
        footer_research_link: "研究",
        footer_projects_link: "项目",
        footer_contact: "联系方式",
        footer_follow: "关注我们",
        footer_rights: "版权所有。"
    }
};

// DOM elements
const languageBtn = document.getElementById('languageBtn');
const languageOptions = document.getElementById('languageOptions');
const currentLang = document.getElementById('currentLang');
const tabBtns = document.querySelectorAll('.tab-btn');
const tabContents = document.querySelectorAll('.tab-content');

// Language selector functionality
languageBtn.addEventListener('click', () => {
    languageOptions.classList.toggle('active');
});

// Close language options when clicking outside
document.addEventListener('click', (e) => {
    if (!languageBtn.contains(e.target) && !languageOptions.contains(e.target)) {
        languageOptions.classList.remove('active');
    }
});

// Language selection
const langLinks = document.querySelectorAll('.language-options a');
langLinks.forEach(link => {
    link.addEventListener('click', (e) => {
        e.preventDefault();
        const lang = link.getAttribute('data-lang');
        changeLanguage(lang);
        languageOptions.classList.remove('active');
    });
});

// Change language function
function changeLanguage(lang) {
    // Update current language display
    const langText = {
        en: 'English',
        es: 'Español',
        ru: 'Русский',
        zh: '中文'
    };
    currentLang.textContent = langText[lang];

    // Update all elements with translation
    const elements = document.querySelectorAll('[data-translate]');
    elements.forEach(element => {
        const key = element.getAttribute('data-translate');
        if (translations[lang] && translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });

    // Store language preference
    localStorage.setItem('selectedLanguage', lang);
}

// Tab functionality
tabBtns.forEach(btn => {
    btn.addEventListener('click', () => {
        const tabId = btn.getAttribute('data-tab');

        // Remove active class from all tabs and contents
        tabBtns.forEach(b => b.classList.remove('active'));
        tabContents.forEach(c => c.classList.remove('active'));

        // Add active class to clicked tab and corresponding content
        btn.classList.add('active');
        document.getElementById(tabId).classList.add('active');
    });
});

// Smooth scrolling for navigation links
document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function (e) {
        e.preventDefault();
        const target = document.querySelector(this.getAttribute('href'));
        if (target) {
            window.scrollTo({
                top: target.offsetTop - 80,
                behavior: 'smooth'
            });
        }
    });
});

// Load saved language preference
const savedLanguage = localStorage.getItem('selectedLanguage');
if (savedLanguage) {
    changeLanguage(savedLanguage);
}